set -sg escape-time 10
set -g focus-events on

set -g status-interval 30
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g mouse on
