[tools]
node = "lts"
python = "3.14"
go = 'latest'
rust = 'latest'
yarn = 'latest'
bun = 'latest'
dotnet = 'latest'

aws-cli = 'latest'
claude = 'latest'
github-cli = 'latest'
jq = 'latest'
neovim = "0.11.4"
ripgrep = 'latest'
starship = 'latest'

[settings]
idiomatic_version_file_enable_tools = ["node"]
