[tools]
node = "lts"
python = "3.14"
go = "1.25"
rust = 'latest'
yarn = 'latest'
bun = 'latest'

aws-cli = 'latest'
jq = 'latest'
github-cli = 'latest'
neovim = "0.11.4"
tokei = 'latest'
ripgrep = 'latest'
starship = 'latest'
opencode = 'latest'

[settings]
idiomatic_version_file_enable_tools = ["node"]
