[tools]
node = 'lts'
python = '3.12'
go = '1.24'
rust = 'latest'
yarn = 'latest'
bun = 'latest'

aws-cli = 'latest'
jq = 'latest'
github-cli = 'latest'
neovim = '0.11.2'
tokei = 'latest'
tmux = 'latest'
ripgrep = 'latest'

[settings]
idiomatic_version_file_enable_tools = ["node"]
